### ISSUE TITLE
Lack of documentation on what format Unreal comments should be in (coding standard)

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#10]
Hello, I'm running Surreal Docs on a large existing project. I understand I will need to modify some code to get the *best possible docs integration*, but I'm lacking documentation on how to do that. 

A large portion of my comments are styled according to this page; https://docs.unrealengine.com/4.26/en-US/ProductionPipelines/DevelopmentSetup/CodingStandard/, but Surreal Docs only seems to offer partial support here. 

An example issue is when I format my comment like this:

```c++
	/**
	 * An example description which is very long, therefor stretching across
	 * multiple lines. 
	 * @param myClass - The class that will be used.
	 */
```

The resulting HTML will interpret the first two lines as a *list*, and create a very ugly description. Is this intended? Is there a workaround? This is where more complete docs would be a huge help. 

I'm also curios about markdown support in this area, or if I'm strictly only supposed to use the "javadoc" style comments.

**Comment by wcobalt** [comment]
Hi @SirLich!

Are we talking about C++ comments or BP?

**Comment by SirLich** [comment]
I'm talking about C++ comments. My assumption is that I should closely follow the Coding Convention outlined in the Unreal Documentation, but that isn't explicitly stated anywhere, and I'm getting some weird results (like multi-line comments being interpreted as a list).

**Comment by wcobalt** [comment]
Can you provide a screenshot?

For me a comment like this
![image](https://github.com/medelfor/surreal-docs/assets/24494830/978486a9-1d15-467c-b380-616bb93be5ea)
gets translated into this:
![image](https://github.com/medelfor/surreal-docs/assets/24494830/a3107b5c-7e89-4b19-b6c8-5ebb6b703283)

**Comment by wcobalt** [comment]
And code like this:
```
	/**
	 * An example description which is very long, therefor stretching across
	 * multiple lines. 
	 * @param myClass - The class that will be used.
	 */
	void Do(int myClass) {};
```
into this:
![image](https://github.com/medelfor/surreal-docs/assets/24494830/95304f9e-444d-4740-94c7-ef73adda2f8a)

**Comment by wcobalt** [comment]
Speaking about documentation, here's a relevant page: https://docs.medelfor.com/medelfor/surreal-docs/1.0.1/en-US/docs/tags

**Comment by SirLich** [comment]
I will provide a proper reproduction tomorrow, with screenshots. It's possible the issues are caused by a missing * in the comment block. i.e., 

```C++
/*
* Something written here, with
* two lines.
*/

Which I can understand could be interpreted as a *list*. If that's the case, then it's definitely on me. Either way, thank you for the documentation link. it appears to be very comprehensive. Thank you for the quick response and the patience!

**Comment by wcobalt** [comment]
Thank you for using Surreal Docs!

Speaking about comments with a missing *, for C++ pages in the docs, such comments will be ignored. For BP pages of the corresponding entities, such comments indeed will translate into a list, like this:
![image](https://github.com/medelfor/surreal-docs/assets/24494830/1a4fd04b-8c4f-42dd-aeb0-dfc446c7bcb3)
Is that the issue you faced?

**Comment by SirLich** [comment]
This seems very likely, yes.
