### ISSUE TITLE
UBlueprintFunctionLibrary fail to be picked up for Blueprint Reference (among others)

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#11]
This is a funny one, and I'm happy to accept I'm at fault here. I tend to write BlueprintFunctionLibraries like this:

```c++
UCLASS()
class MYCLASS_API UMyFunctionLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
```

This style has a raw `UCLASS()` which I believe causes the generator to skip it entirely, completely ignoring the juicy exposed functions inside. While I can understand the idea behind this, it's a bit weird. I think the solution is to add something like `MinimalApi` or one of the other blueprint-class exposures? 

If you check engine code you can find a lot of examples of 'UBlueprintFunctionLibrary' defined without any additional `UCLASS` metadata, so honestly I'm not sure whether to treat this as a bug in Surreal Docs, or a coding-convention-violation on my part :)

**Comment by SirLich** [comment]
Here is an example from the engine, which shows writing `BlueprintFunctionLibary` without exposing the wrapper class to Blueprint:

```c++
/**
 * Inherits from UBlueprintFunctionLibrary to allow exposure to Blueprint Library in the same class.
 */
UCLASS()
class LIDARPOINTCLOUDRUNTIME_API ULidarPointCloudFileIO_ASCII : public UBlueprintFunctionLibrary, public FLidarPointCloudFileIOHandler
```

**Comment by SirLich** [comment]
To avoid spamming the issues page, I would also note I'm having this issue in the following places:
 - UDeveloperSettings
 - UWorldSubsystem (and other subsystems)
 
 The common thread is that these classes are *implicitly available to Blueprint, without anything explicit added to the UCLASS definition*

**Comment by wcobalt** [comment]
That's an interesting one! I'll look into the relevant code ASAP, and most probably the fix will be available in `1.1.0`

**Comment by SirLich** [comment]
Thanks for the quick response. I will test tomorrow with some explicit exposure (like MinimalAPI as I mentioned, or maybe something else). 

But since they're implicitly exposed, it would be awesome if Surreal Docs would just handle it :)

**Comment by SirLich** [comment]
Update: As expected adding 'BlueprintType' here works. This still isn't desired though -more of a 'workaround'.

**Comment by alicewlx** [comment]
Hi @SirLich!

Everything what is derived  from `UDeveloperSettings`, `USubsystem`, `UBlueprintFunctionLibrary` is exported now in [1.1.0](https://github.com/medelfor/surreal-docs/releases/tag/1.1.0 "Surreal Docs 1.1.0")
