### ISSUE TITLE
[Feature Request] Classes do not list their children

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#12]
For example, if I have a `UAnimal` class, with child-classes `UDog` and `UCat`. 

On the `UDog` page, it contains everything I would want, making it clear that `UDog` inherits from `UAnimal`. The integration is very nice. 

But on the `UAnimal` page, there is no list of 'child classes (i.e., listing `UDog` and UCat`). This would be very helpful in object oriented code-bases.

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1205](https://issues.internal.medelfor.com/youtrack/issue/SD-1205/Classes-do-not-list-their-children). If necessary new comments can be added in the YouTrack's issue (preferably) or here.
