### ISSUE TITLE
[Bug] 'surdocs init' does not allow removing modules

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#13]
Version: `v1.1.0` (pre release, I guess)

When I use `surdocs init` I can select/unselect various modules. Adding modules works, and persists to the next init/generate session. However *removing* modules doesn't work; the next time I run 'init' the modules will show again, and the next time I run 'generate' they will be generated. 

I will try and dig into the configuration files of surreal docs to see if I can remove these unwanted modules by hand, but naturally it would be cool if the `init` command would support this.

**Comment by SirLich** [comment]
Update: I managed to just edit `surreal.json`. So it's a low-impact issue, but I thought I would report it anyways :)

**Comment by alicewlx** [comment]
Hi @SirLich!

Modules management with `init` is fully-functional in [1.1.0](https://github.com/medelfor/surreal-docs/releases/tag/1.1.0 "Surreal Docs 1.1.0")

**Comment by SirLich** [comment]
Awesome! I can test it, or you can likely just close this :)

**Comment by alicewlx** [comment]
Hi!

It'd be great if you could give it a try, just to make sure that the issue is actually resolved.

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1198](https://issues.internal.medelfor.com/youtrack/issue/SD-1198/Modules-cannot-be-removed-via-init)
