### ISSUE TITLE
`BlueprintNativeEvent`/`BlueprintImplementableEvent` without `BlueprintCallable` does not show up inside of the documentation

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#14]
I have a `UINTERFACE(BlueprintType)` with a number of `BlueprintNativeEvent` defined inside (note: BlueprintCallable is not added, since it's not acceptable for blueprint functions to call these methods; only implement them). 

The C++ documentation looks *great*, but the blueprint documentation is lacking. While it does generate a page for the interface, it doesn't contain any of the BlueprintNativeEvent functions.

Here is an example from Epic, which closely mirrors my implementation. Hopefully this helps:

```C++
// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Interface.h"
#include "IVPInteraction.generated.h"

class UVirtualScoutingInteraction;

// This class does not need to be modified.
UINTERFACE(BlueprintType)
class UVPInteraction : public UInterface
{
	GENERATED_BODY()
};

class IVPInteraction : public IInterface  
{
	GENERATED_BODY()

	// Add interface functions to this class. This is the class that will be inherited to implement this interface.
public:

	/** Called when actor is dropped from Carry state by the VREd interactor */
	UFUNCTION(BlueprintNativeEvent, CallInEditor, BlueprintCallable, Category = "VirtualScouting|Interaction")
	void OnActorDroppedFromCarry();

	/** Called when an actor is selected by the VREd interactor */
	UFUNCTION(BlueprintNativeEvent, CallInEditor, BlueprintCallable, Category = "VirtualScouting|Interaction")
	void OnActorSelectedForTransform();

	/** Called when dropped by VRTool */
	UFUNCTION(BlueprintNativeEvent, CallInEditor, BlueprintCallable, Category = "VirtualScouting|Interaction")
	void OnActorDroppedFromTransform();
};
```

**Comment by SirLich** [comment]
EDIT: If I add `BlueprintCallable` to these events, they do indeed begin generating. I will edit the title of the issue. 

I believe the behavior should be adjusted to pick up `BlueprintNativeEvents` without requiring `BlueprintCallable`, as it's a perfectly valid configuration -and a valid one, when you don't want blueprint developers calling the methods :)

**Comment by SirLich** [comment]
Update: This is also an issue for `BlueprintImplementableEvent`

**Comment by wcobalt** [comment]
The idea for this behaviour was that in case when BP-user cannot call a function it shouldn't be in the BP documentation. I'm still not sure whether we should show them, when they're just supposed to be implemented

**Comment by SirLich** [comment]
I understand the idea behind it, although from my perspective it's the wrong approach. 

When a blueprint developer implements an interface, or inherits from a base class, they should be able to see in the documentation the available methods to implement.

Another idea here is to have something "outside" of Unreals normal syntax scope, which forces it to be picked up. Like for example `meta=ExposeDocs` which is read from the meta-struct, and used to force exposure even when the properties would normally hide it.

**Comment by wcobalt** [comment]
Alight, for the time being we'll enable exposure of `BlueprintImplementableEvent` and `BlueprintNativeEvent`, but we'll give it more thought later. Maybe we'll add a switch for these two or a meta-flag as you proposed

**Comment by alicewlx** [comment]
Hi @SirLich!

Everything overridable in Blueprints is exported in [1.1.0](https://github.com/medelfor/surreal-docs/releases/tag/1.1.0 "Surreal Docs 1.1.0")

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1202](https://issues.internal.medelfor.com/youtrack/issue/SD-1202/BlueprintNativeEvent-BlueprintImplementableEvent-without-BlueprintCallable-does-not-show-up-inside-of-the-documentation)
