### ISSUE TITLE
Using bad @ref causes hang at 43% (Processing documentation tree)

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#15]
After becoming stuck, the entire 'cmd' or 'powershell' (I tried both) window becomes very broken, and starts spamming like this:

![image](https://github.com/medelfor/surreal-docs/assets/18729296/19fa598e-530e-4885-9c67-7c49b8b61511)

Now, the issue in this case was a bad `@ref class::UMyClass` element that I added, but I could only discover this by guessing/checking what I had just added. The logs were not helpful. 

Not a huge deal, since the error was on my side, but it would be nice if Surreal Docs would print a warning and then continue generating documentation (as it does for bad @see refs), rather than just dying.

**Comment by wcobalt** [comment]
> Could you please show the comment which included the @ref?
It's not necessary anymore, I was able to reproduce the issue. The fix will go into `1.1.0` which we're releasing tomorrow or the day after tomorrow.

**Comment by alicewlx** [comment]
Hi @SirLich!

We've fixed the `SEGFAULT` in [1.1.0](https://github.com/medelfor/surreal-docs/releases/tag/1.1.0 "Surreal Docs 1.1.0")

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1199](https://issues.internal.medelfor.com/youtrack/agiles/121-2/current?issue=SD-1199)
