### ISSUE TITLE
[Feature Request] Sort modules into the plugins which contain them

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#16]
This is obviously a 'nice to have' more than anything, but it would be nice if modules are sorted into the plugin which wraps them. For example, if you have a plugin called `Zoo`, it's fairly common to have modules such as `ZooEditor`, `ZooRuntime`, and `ZooUtilities`, or some other combination of modules.

It would be cool if you would use the `"FriendlyName"` and `"Description"` fields of the .uplugin file to add some structure to the page. 

So something like this (not sure how github would render it):

# Project Name

### Project Module

# Plugins

### ZooRuntime

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1206](https://issues.internal.medelfor.com/youtrack/issue/SD-1206/Group-modules-by-the-plugins-which-contain-them)
