### ISSUE TITLE
[Feature Request] Support @warning and @note 

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#17]
@warning is listed on the unreal coding convention as a valid @ classifier: https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/DevelopmentSetup/CodingStandard/

@note is not listed here, but could be cool to implement, if @warning is implemented. 

The idea is you pull the line, and enclose it in the modal system you're using elsewhere (surreal markdown): 
![image](https://github.com/medelfor/surreal-docs/assets/18729296/aff9813f-e6ee-41ca-b25a-9726b8b15f1c)

**Comment by alicewlx** [comment]
Hi @SirLich!

You've made several features request recently, namely:
 - #17 
 - #16 
 - #12 

May I ask you to rate how critical these features are to your project(s) on the scale from 1 to 5? Where 1 is "Not critical at all" and 5 is "Very critical"

**Comment by SirLich** [comment]
None of them are that critical :)

Support 'Warning': 2
Sort modules into plugins: 2
Classes do not list their children: 3

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1107](https://issues.internal.medelfor.com/youtrack/issue/SD-1107/Support-of-notewarning-in-C-BP)
