### ISSUE TITLE
Absolute file path is not a good idea in surdocs/surreal.json

### ISSUE THREAD

**Issue by PrimaryFantasty** [medelfor/surreal-docs#19]
![image](https://github.com/medelfor/surreal-docs/assets/36122477/d6119fa8-0efa-4a46-8712-72b60beab90c)
That make a bad experience when I share my docs config.

**Comment by alicewlx** [comment]
Sorry for the inconvenience!

Yes, absolutely, that was a bad decision. We're aware of the problem and are aiming to fix it in the next release.

**Comment by PrimaryFantasty** [comment]
Thank you very much!
And  the ue root configuration: 
![image](https://github.com/medelfor/surreal-docs/assets/36122477/ad775ed5-378d-4641-90f1-74106b19515c)

**Comment by alicewlx** [comment]
Regarding UE Root, I don't actually see any other options, since relatively to the project's directory the UE root is always located differently, what means relative paths cannot be used. The only option is to use absolute ones.

**Comment by PrimaryFantasty** [comment]
> 关于 UE Root，我实际上没有看到任何其他选项，因为相对于项目目录，UE 根总是位于不同的位置，这意味着不能使用相对路径。唯一的选择是使用绝对值。

Yeah, my approach is : 
![image](https://github.com/medelfor/surreal-docs/assets/36122477/e046bbca-5760-4e08-94c8-4855e96ea619)
Or `surdoc gen -ueRoot F:\\ue\\UE_5.0`? But it doesn't matter, hah~
By the way, good job you are doing now.

**Comment by alicewlx** [comment]
Thank you!

We will consider adding an ability to specify the root via an env. variable or CLI option

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1207](https://issues.internal.medelfor.com/youtrack/issue/SD-1207/Get-rid-of-absolute-paths-in-surreal.json)
