### ISSUE TITLE
Plugin core module type should be "Editor", because of shipping package.

### ISSUE THREAD

**Issue by PrimaryFantasty** [medelfor/surreal-docs#20]
![image](https://github.com/medelfor/surreal-docs/assets/36122477/1648df6c-dd24-437a-8f12-97b394d4a78f)

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1208](https://issues.internal.medelfor.com/youtrack/issue/SD-1208)
