### ISSUE TITLE
Is it possible to detect documentation comments for .cpp, .cc, .hpp, etc.?

### ISSUE THREAD

**Issue by PrimaryFantasty** [medelfor/surreal-docs#3]

**Comment by wcobalt** [comment]
Hey @PrimaryFantasty!

Header files with extensions different to `.h` are already supported. It includes `.hpp`, `.hxx`, `.hh` and `.h++`. Regarding extracting doc comment from implementation files it is disabled at the moment, but we're considering adding such ability. You can track progress of the task [here](https://issues.internal.medelfor.com/youtrack/issue/SD-1187/Add-a-switch-which-enables-gathering-of-data-from-implementation-files-.cc-.cpp-and-such). ETA is no earlier than the end of June

**Comment by alicewlx** [comment]
Hi @PrimaryFantasty!

May I ask, how critical is this feature to your project(s) on the scale from 1 to 5? Where 1 is "Not critical at all" and 5 is "Very critical"

**Comment by alicewlx** [comment]
I see. Thank you for the detailed answer!

**Comment by alicewlx** [comment]
The issue was moved to YouTrack. It's available as [SD-1187](https://issues.internal.medelfor.com/youtrack/issue/SD-1187/Add-a-switch-which-enables-gathering-of-data-from-implementation-files-.cc-.cpp-and-such). If necessary new comments can be added in the YouTrack's issue (preferably) or here.
