### ISSUE TITLE
Perhaps it's not ideal to back up and modify project files.

### ISSUE THREAD

**Issue by PrimaryFantasty** [medelfor/surreal-docs#5]
Backing up and modifying .uproject file may contaminate project structure, which is not ideal. Instead, you can use the option 'EnabledByDefault: true' in  UnrealisticDocs plugin as a replacement, is it ok?

**Comment by wcobalt** [comment]
Hey @PrimaryFantasty!

Thank you for the idea we will definitely consider that

**Comment by alicewlx** [comment]
Hi @PrimaryFantasty!

The proposed change was implemented in [1.1.0](https://github.com/medelfor/surreal-docs/releases/tag/1.1.0 "Surreal Docs 1.1.0"), thank you!

I'll be closing the issue, feel free to reopen it in case something doesn't work as expected.
