### ISSUE TITLE
Generated images are all corrupted

### ISSUE THREAD

**Issue by Penguin-Soup** [medelfor/surreal-docs#6]
After generating the documentations via 'surdocs generate [output directory]', all the generated images such as plain_float_.png are all corrupted, and are not visible in the documentation. I've made sure to install surrealdocs, surrealdocs cli and node.js from the binary installer.

During the initialisation, I've chosen an Editor Target, selected to hide private members and tried both development and shipping configuration.

The default surrealdoc icons are all fine however, it's just the images in the _generated folder such as blueprint nodes and icons that are problematic.

**Comment by wcobalt** [comment]
Hi @Penguin-Soup, sorry for the inconvenience! 

Could you please open one of the corrupted files and tell me whether it's empty or contains some content?
Also it would be great if you could attach the logs. They should be located under `%AppData%/Medelfor/SurrealDocs/logs`.
Also could you please open CMD or PowerShell and execute: `npm --version` and `node --version`? (as described [here](https://docs.medelfor.com/medelfor/surreal-docs/latest/en-US/docs/installation).

**Comment by Penguin-Soup** [comment]
Thanks for the quick reply!

The images are empty (0 bytes in size) and does not contain any  content.

Log:
[SD-log-2023.06.21_16-41-53.log](https://github.com/medelfor/surreal-docs/files/11814363/SD-log-2023.06.21_16-41-53.log)

The npm version is 9.5.1, and the node version is v18.16.0

**Comment by wcobalt** [comment]
In the logs I see, that Node packages didn't get installed.

Could you please navigate to `%AppData%/Medelfor/SurrealDocs` and check whether it contains `package.json`, `package-lock.json` files and `node_modules` folder? In case it does contain at least `package.json`, please run `npm install` in this directory

**Comment by Penguin-Soup** [comment]
The file path did contain package.json and package-lock.json, but it did not contain node_modules folder. I ran npm install and this is the output:

"added 201 packages, and audited 202 packages in 29s

14 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (5 moderate, 3 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details."

Should I run any of the 'npm audit fix' command, or is that unncessary? I do have the node_modules folder in the directory now.

**Comment by wcobalt** [comment]
No, it's not necessary.

Now please try to run `surdocs generate <out>` to see whether it fixed the problem

**Comment by wcobalt** [comment]
May I also ask whether the installation process finished correctly when you were installing Surreal Docs? By "correctly" I mean that in the end a "Successful installation" screen should have been shown by installer. Also do you have any antivirus applications installed, except for Windows' built-in?

**Comment by Penguin-Soup** [comment]
I generated the documentation again, but the images are still corrupted (0 bytes).

The installer did notify that Puppeteer failed to install and that it needed manual installation, which I did via running `npm i puppeteer` in the CMD.

The other thing was that during the node.js installation, I did not select to install Chocoltey as it kept failing to install before.

Regarding anti-virus, I do not have any antivirus applications except for Window's Defender (built-in).

**Comment by wcobalt** [comment]
I see. Could you please navigate to `C:\Program Files\Medelfor\SurrealDocs` (disk symbol can be different) and check whether it contains a shortcut/junction to `node_modules` (probably it doesn't). If it doesn't please open CMD (not PowerShell) with administrator privileges and run the following command:
```
mklink /J node_modules "%AppData%/Medelfor/SurrealDocs/node_modules"
```
Did it create the junction to the `node_modules` inside the `C:\Program Files\Medelfor\SurrealDocs`? If it did please run generation again.

**Comment by Penguin-Soup** [comment]
It did not contain a junction to node_modules, so I ran the command which created it.

After running the generation again, it now has the images correctly generated! No corruption anymore. 

Thank you for the help! SurrealDocs is an amazing and conveneint software, so I am glad everything is working correctly now.

**Comment by wcobalt** [comment]
Thank you a lot!

These were all steps that failed during installation. However it's still unclear why they failed, but we will investigate that.

Consider giving us a star if you think Surreal Docs is worth it.

**Comment by Penguin-Soup** [comment]
Sure thing! Where can I give the star? In the Surreal Docs site?

**Comment by wcobalt** [comment]
No, I meant here on GitHub
![image](https://github.com/medelfor/surreal-docs/assets/24494830/ac40c020-f8a4-4eae-a5a0-84c79818f2a9)

**Comment by SirLich** [comment]
Hi, I am facing the same issue on my end. Here are some stats from my side:
 - npm: 9.5.1
 - node: v18.16.0
 
 Unlike the original poster, my 'node_modules' folder already existed. Here is the log from `npm install`:

```
up to date, audited 203 packages in 3s

14 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (9 moderate, 3 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

From my understanding, this means it didn't install any packages at all. I didn't run any 'audit/fix' commands.  When I check, my image are `0 bytes`, as described.

The directory junction already existed for me as well, inside of 'C:\Program Files\Medelfor\SurrealDocs'. I think the issue might be caused by the fact that my `node_modules` directory is installed under an admin account, so even though I'm running the command with an authenticated powershell session, it might be failing.

**Comment by alicewlx** [comment]
Hi @SirLich, sorry for the inconvenience!

Could you please clarify whether the `npm --version` and `node --version` work with the same user you're running `surdocs generate` under? Also it'd be great if you could attach the logs from the problematic generation session.

Note that `node_modules` are getting installed to `%appdata%` of the user that performs installation. If user then running `surdocs generate` is not the same user that installed the tool, then they have another `%appdata%` what can cause described behaviour. In `1.1.0` version, we've changed installation directory of `node_modules` to `%ProgramData%`, so it'd be common for all users.

**Comment by alicewlx** [comment]
Here's a link to release candidate for `1.1.0`, you can try it out to see if that fixes the issue: https://storage.googleapis.com/deployed.medelfor.com/prod/udocs-processor/installer/win64/SurrealDocs-v1.1.0-x64.exe

**Comment by SirLich** [comment]
Thanks for the quick response! The version numbers for `npm` and `node` were indeed from the same Admin account with which I installed and run Surreal Docs. 

> Here's a link to release candidate for 1.1.0

I will try this as soon as possible, thanks :)

> Note that node_modules are getting installed to %appdata% of the user that performs installation. If user then running surdocs generate is not the same user

Yeah I noticed this as well. I will also be trying to reinstall with a new user, to see if that helps.

**Comment by SirLich** [comment]
I updated to 1.1.0, and also installed "normally" (my original installation was messed up in some subtle ways). Image generation is working now :)

**Comment by alicewlx** [comment]
In [1.1.0](https://github.com/medelfor/surreal-docs/releases/tag/1.1.0 "Surreal Docs 1.1.0") we've got rid of Node dependency, so issues like this one should not appear anymore.

Feel free to reopen the issue in case something doesn't work as expected.
