### ISSUE TITLE
UnrealisticDoc build fails becase it can't load UnrealEd Module

### ISSUE THREAD

**Issue by lifeisforu** [medelfor/surreal-docs#7]
HI.

I'm trying to use Surreal-Docs. 

But I fails to generate docs, because UBT error occurs.

`Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
(referenced via Target -> UnrealisticDocs.Build.cs)
BuildException: Unable to instantiate UnrealEd module for non-editor targets.`

UnrealisticsDoc plugin use "UnrealEd" module, but it is built by "Development" configuration.

I guessed it must be built with "XXX Editor" configuration. It's right?

So I changed configuration in "surreal.json" like below.

`    "ue": {
        "configuration": "Development Editor",
        "root": "C:\\p4\\UE5\\",
        "target": "WNAbilityTest"
    },`

But there's no effect by changing configuration. 

Let me know how can I generate docs.

Thanks.

[UBT-WNAbilityTest-Win64-Development.txt](https://github.com/medelfor/surreal-docs/files/11861396/UBT-WNAbilityTest-Win64-Development.txt)

**Comment by lifeisforu** [comment]
I fix this problem, changing UnrealisticDocs.Build.cs.

`/* Copyright © 2022, Medelför OÜ. All rights reserved. */

using System;
using UnrealBuildTool;
using System.IO;

public class UnrealisticDocs : ModuleRules
{
	public UnrealisticDocs(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
		bEnforceIWYU = true;
		bUseUnity = false;

		String Private = Path.Combine(ModuleDirectory, "Private");

		PrivateIncludePaths.Add(Private);
		PrivateIncludePaths.Add(Path.Combine(Private, "Enumeration"));

		//@todo remove RHI
		PrivateDependencyModuleNames.AddRange(
			new string[]
			{
				"Core",
				"CoreUObject",
				"Engine",
				"InputCore",
				"Json",
				"JsonUtilities",
				"UMG"
			}
		);

		if (Target.bBuildEditor)
		{
            PrivateDependencyModuleNames.AddRange(
            new string[]
            {
                "UnrealEd",
                "PropertyEditor",
                "EditorStyle",
                "GraphEditor",
                "BlueprintGraph",
                "MainFrame",
            });
        }
}`

Please release new binary for this bug-fix.

**Comment by wcobalt** [comment]
Hey @lifeisforu!

You shouldn't change Build.cs, what you should do is select an *Editor target when running `init`. In the `surreal.json` you've shown there's an erroneous space between Development and Editor

**Comment by lifeisforu** [comment]
> 

There's no `*Editor` Configuration int `init` menu.

![init](https://github.com/medelfor/surreal-docs/assets/11884712/8c301e1b-a88e-474c-a98b-aa970ff5e644)

**Comment by wcobalt** [comment]
I apologize, I meant Target of course: WNAbilityTestEditor in your case

**Comment by lifeisforu** [comment]
> 

Thank you for your fast reply. I'll try it.

**Comment by lifeisforu** [comment]
Thank you for good support. Have a nice day.

![success](https://github.com/medelfor/surreal-docs/assets/11884712/c63ae5a6-f394-42c2-bf44-a4bb84ef433c)

**Comment by wcobalt** [comment]
Thank you! Consider giving Surreal Docs a star if you think it deserves it
