### ISSUE TITLE
'Last updated 58 years ago' (old timestamps on pages)

### ISSUE THREAD

**Issue by SirLich** [medelfor/surreal-docs#9]
Pages seem to generate with an absurd timestamp. This is also the case for the example documentation. I'm using Surreal Docs v1.0.5. This isn't a huge deal, but could be nice to fix eventually.

**Comment by wcobalt** [comment]
Will try to get fixed in `1.1.0`. At least for locally generated HTML

**Comment by alicewlx** [comment]
Hi @SirLich!

The timestamps were fixed in [1.1.0](https://github.com/medelfor/surreal-docs/releases/tag/1.1.0 "Surreal Docs 1.1.0")
